#include "DigiKeyboard.h"
void setup(){}
void loop() {
  DigiKeyboard.sendKeyStroke(0);
  DigiKeyboard.delay(500);
  DigiKeyboard.delay(500);
  DigiKeyboard.sendKeyStroke(21, 8);
  DigiKeyboard.delay(200);
  DigiKeyboard.print("notepad.exe");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.delay(300);
  DigiKeyboard.print("          , ,\ ,'\,'\ ,'\ ,\ ,");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("    ,  ,\/ \' `'     `   '  /|");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("    |\/                      |");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("    :                        |");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("    :                        |");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     |                       |");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     |                       |");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     :               -.     _|");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     :                \     `.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     |         ________:______\");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     :       ,'o       / o    ,");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     :       \       ,'-----./");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("      \_      `--.--'        )");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     ,` `.              ,---'|");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     : `                     |");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("      `,-'                   |");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("      /      ,---.          ,'");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("   ,-'            `-,------'");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("   `.        ,--'");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("     `-.____/");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("            \");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("I will learn to lock my computer.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("There, just like Bart Simpson.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("Please remember to lock your computer (Windows+L) when you step away from your desk.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.print("Thank you.");
  DigiKeyboard.sendKeyStroke(40);
  DigiKeyboard.delay(100);
  DigiKeyboard.sendKeyStroke(44, 4);
  DigiKeyboard.print("x");
  DigiKeyboard.delay(50);
  DigiKeyboard.sendKeyStroke(15, 8);
}
